// Generated by scripts/generate-config.js from .env — do not edit directly.
// This file IS committed: SUPABASE_PUBLISHABLE_KEY is the public anon key,
// safe to ship in client code. Row Level Security policies on each table
// are what actually control access, not secrecy of this key. GitHub Pages
// serves this repo's files with no build step, so committing the generated
// output is what makes the site work at all — regenerate with `npm run
// build` after changing .env, then commit the result.
export const SUPABASE_URL = "https://ckyvveuqnamezqzcqobr.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ht9N0WTK5TOG65VbxPC-Bg_lUR6DHsn";
