#!/usr/bin/env node
// Reads Supabase connection details from environment variables (loaded from
// .env locally, or set in the hosting platform's dashboard for deploys) and
// writes js/config.js, which the browser loads as a plain ES module. This
// keeps the values out of git history while still working on a static host
// with no server-side runtime.
const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const envPath = path.join(rootDir, '.env');

if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}

const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = process.env;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    'Missing SUPABASE_URL and/or SUPABASE_PUBLISHABLE_KEY.\n' +
      'Copy .env.example to .env and fill in real values, then run this again.'
  );
  process.exit(1);
}

const output = `// Generated by scripts/generate-config.js from .env — do not edit directly,
// and do not commit this file (it's gitignored).
export const SUPABASE_URL = ${JSON.stringify(SUPABASE_URL)};
export const SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(SUPABASE_PUBLISHABLE_KEY)};
`;

fs.writeFileSync(path.join(rootDir, 'js', 'config.js'), output);
console.log('Wrote js/config.js');
